const express = require('express');
const router = express.Router();
const db = require('../../db');
const { authenticateUser } = require('../auth/middleware');
const PDFDocument = require('pdfkit');
const QRCode = require('qrcode');

// --- HELPER: FETCH SACCO BRANDING ---
async function getSaccoDetails() {
    const res = await db.query("SELECT setting_key, setting_value FROM system_settings WHERE category = 'SACCO' OR setting_key LIKE 'sacco_%'");
    const settings = {};
    res.rows.forEach(r => settings[r.setting_key] = r.setting_value);
    return {
        name: settings['sacco_name'] || 'Sacco System',
        address: settings['sacco_address'] || 'P.O Box 12345, Nairobi, Kenya',
        email: settings['sacco_email'] || 'info@sacco.com',
        phone: settings['sacco_phone'] || '+254 700 000 000',
        logo: settings['sacco_logo'] // Expecting Base64 string (data:image/png;base64,...)
    };
}

// --- HELPER: DRAW BANK HEADER ---
async function drawHeader(doc, title, user, details, serialNo) {
    // 1. Draw Logo (if exists)
    if (details.logo && details.logo.startsWith('data:image')) {
        try {
            const imgData = details.logo.split(',')[1];
            const imgBuffer = Buffer.from(imgData, 'base64');
            doc.image(imgBuffer, 50, 45, { width: 60 });
        } catch (e) { console.error("Logo Error:", e); }
    }

    // 2. Sacco Details (Right Aligned)
    doc.font('Helvetica-Bold').fontSize(16).text(details.name, 200, 50, { align: 'right' });
    doc.font('Helvetica').fontSize(9).text(details.address, 200, 70, { align: 'right' });
    doc.text(`Tel: ${details.phone} | Email: ${details.email}`, 200, 85, { align: 'right' });
    doc.moveDown();

    // 3. Title & Separator
    doc.moveTo(50, 110).lineTo(550, 110).strokeColor('#aaaaaa').stroke();
    doc.font('Helvetica-Bold').fontSize(14).fillColor('#333333').text(title.toUpperCase(), 50, 120, { align: 'center', characterSpacing: 1 });
    
    // 4. Member & Statement Details (Two Columns)
    const topY = 150;
    
    // Left: Member Info
    doc.fontSize(10).fillColor('black');
    doc.font('Helvetica-Bold').text('MEMBER DETAILS:', 50, topY);
    doc.font('Helvetica').text(user.full_name.toUpperCase(), 50, topY + 15);
    doc.text(`Member ID: ${user.id_number || 'N/A'}`, 50, topY + 30);
    doc.text(`Phone: ${user.phone_number}`, 50, topY + 45);
    doc.text(`Email: ${user.email}`, 50, topY + 60);

    // Right: Statement Info
    doc.font('Helvetica-Bold').text('STATEMENT DETAILS:', 350, topY);
    doc.font('Helvetica').text(`Date: ${new Date().toDateString()}`, 350, topY + 15);
    doc.text(`Serial No: ${serialNo}`, 350, topY + 30);
    doc.text(`Generated By: SYSTEM`, 350, topY + 45);

    // 5. Generate QR Code (Authenticity)
    // Data: "VERIFIED | [Serial] | [User] | [Date]"
    const qrString = `VERIFIED STATEMENT | ${details.name} | Ref:${serialNo} | Member:${user.full_name}`;
    const qrData = await QRCode.toDataURL(qrString);
    const qrBuffer = Buffer.from(qrData.split(',')[1], 'base64');
    doc.image(qrBuffer, 480, topY - 10, { width: 70 });

    doc.moveDown(4);
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.moveDown(0.5);
}

// ============================================================================
// ROUTE 1: MEMBER STATEMENT (Official Bank Template)
// ============================================================================
router.get('/statement/me', authenticateUser, async (req, res) => {
    try {
        const userId = req.user.id;
        const serialNo = `STMT-${new Date().getFullYear()}-${Math.floor(100000 + Math.random() * 900000)}`;

        // Fetch Data
        const [userRes, txRes, sacco] = await Promise.all([
            db.query("SELECT * FROM users WHERE id = $1", [userId]),
            db.query("SELECT * FROM transactions WHERE user_id = $1 ORDER BY created_at ASC", [userId]),
            getSaccoDetails()
        ]);
        
        const user = userRes.rows[0];
        const transactions = txRes.rows;

        // Init PDF
        const doc = new PDFDocument({ margin: 50, size: 'A4' });
        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', `attachment; filename=${serialNo}.pdf`);
        doc.pipe(res);

        // Draw Header
        await drawHeader(doc, 'Account Statement', user, sacco, serialNo);

        // --- TABLE HEADERS ---
        let y = doc.y + 20;
        const colDate = 50;
        const colDesc = 130;
        const colRef = 280;
        const colDebit = 360;  // Money Out
        const colCredit = 430; // Money In
        const colBal = 500;

        // Background for Header
        doc.rect(50, y - 5, 500, 20).fill('#f0f0f0').stroke();
        doc.fillColor('#333333');
        
        doc.font('Helvetica-Bold').fontSize(9);
        doc.text('DATE', colDate, y);
        doc.text('DESCRIPTION', colDesc, y);
        doc.text('REF', colRef, y);
        doc.text('MONEY OUT', colDebit, y);
        doc.text('MONEY IN', colCredit, y);
        doc.text('BALANCE', colBal, y);
        
        y += 25;
        doc.font('Helvetica').fontSize(8);

        // --- TABLE ROWS ---
        let runningBalance = 0;
        let totalIn = 0;
        let totalOut = 0;

        transactions.forEach((tx, i) => {
            if (y > 720) { doc.addPage(); y = 50; } // Auto-page break

            const amt = parseFloat(tx.amount);
            
            // Logic: Is it Money In or Out?
            // Usually in DB: +ve is Deposit, -ve is Withdrawal/Fee
            // OR based on Type if you store absolute numbers
            let moneyIn = 0;
            let moneyOut = 0;
            
            // Adjust this logic based on your specific DB storage:
            // Assuming your 'transactions' table stores POSITIVE numbers for everything
            // and we rely on 'type' to know direction.
            
            const IN_TYPES = ['DEPOSIT', 'LOAN_DISBURSEMENT', 'DIVIDEND'];
            // const OUT_TYPES = ['WITHDRAWAL', 'LOAN_REPAYMENT', 'FINE', 'FEE_PAYMENT', 'REGISTRATION_FEE'];

            if (IN_TYPES.includes(tx.type)) {
                moneyIn = amt;
                runningBalance += amt;
                totalIn += amt;
            } else {
                // Assume everything else is Money Out
                moneyOut = amt;
                runningBalance -= amt; // Deduct
                totalOut += amt;
            }

            // Alternating Row Background
            if (i % 2 === 0) {
                doc.rect(50, y - 2, 500, 14).fillColor('#fbfbfb').fill();
                doc.fillColor('#000000'); // Reset text color
            }

            // Draw Text
            doc.text(new Date(tx.created_at).toISOString().split('T')[0], colDate, y);
            doc.text(tx.description || tx.type, colDesc, y, { width: 140, ellipsis: true });
            doc.text(tx.reference_code || '-', colRef, y);
            
            if(moneyOut > 0) doc.fillColor('#b91c1c').text(moneyOut.toLocaleString(), colDebit, y);
            else doc.text('-', colDebit, y);

            if(moneyIn > 0) doc.fillColor('#047857').text(moneyIn.toLocaleString(), colCredit, y);
            else doc.text('-', colCredit, y);

            doc.fillColor('#000000').text(runningBalance.toLocaleString(), colBal, y);

            y += 15;
        });

        // --- SUMMARY FOOTER ---
        y += 10;
        doc.moveTo(50, y).lineTo(550, y).stroke();
        y += 10;
        
        doc.font('Helvetica-Bold').fontSize(10);
        doc.text('TOTALS:', colRef, y);
        doc.fillColor('#b91c1c').text(totalOut.toLocaleString(), colDebit, y);
        doc.fillColor('#047857').text(totalIn.toLocaleString(), colCredit, y);
        doc.fillColor('#000000').text(`CLOSING: ${runningBalance.toLocaleString()}`, colBal - 20, y);

        // --- OFFICIAL FOOTER ---
        const bottomY = 730;
        doc.fontSize(8).fillColor('grey');
        doc.text('This is a system-generated document. No signature required.', 50, bottomY, { align: 'center' });
        doc.text(`Digital Signature: ${Math.random().toString(36).substring(2, 15).toUpperCase()}-SECURE`, 50, bottomY + 12, { align: 'center' });

        doc.end();

    } catch (err) {
        console.error("Statement Error:", err);
        if (!res.headersSent) res.status(500).json({ error: "Failed to generate PDF" });
    }
});

// ============================================================================
// ROUTE 2: CHAIRPERSON/ADMIN REPORT (Official Executive Template)
// ============================================================================
router.get('/summary/download', authenticateUser, async (req, res) => {
    try {
        if (!['ADMIN', 'CHAIRPERSON', 'TREASURER'].includes(req.user.role)) {
            return res.status(403).json({ error: "Access Denied" });
        }

        const serialNo = `EXEC-${new Date().getFullYear()}-${Math.floor(Math.random() * 1000)}`;
        const sacco = await getSaccoDetails();

        // Data Fetching (Recalculated for fresh PDF)
        const savingsRes = await db.query("SELECT COALESCE(SUM(amount), 0) as total FROM deposits WHERE status = 'COMPLETED' AND type = 'DEPOSIT'");
        const netSavings = parseFloat(savingsRes.rows[0].total);

        const revenueRes = await db.query("SELECT COALESCE(SUM(amount), 0) as total FROM transactions WHERE type IN ('FINE', 'PENALTY', 'REGISTRATION_FEE', 'LOAN_FORM_FEE', 'FEE_PAYMENT')");
        const totalRevenue = parseFloat(revenueRes.rows[0].total);

        const loansRes = await db.query(`SELECT COUNT(*) as count, COALESCE(SUM(amount_requested), 0) as principal, COALESCE(SUM(interest_amount), 0) as interest, COALESCE(SUM(amount_repaid), 0) as repaid, COALESCE(SUM(total_due), 0) as total_due FROM loan_applications WHERE status = 'ACTIVE'`);
        const loanStats = loansRes.rows[0];
        const outstanding = parseFloat(loanStats.total_due) - parseFloat(loanStats.repaid);

        const liquidityRes = await db.query(`SELECT COALESCE(SUM(CASE WHEN type IN ('DEPOSIT', 'LOAN_REPAYMENT', 'FINE', 'PENALTY', 'REGISTRATION_FEE') THEN amount ELSE 0 END), 0) as inflow, COALESCE(SUM(CASE WHEN type IN ('LOAN_DISBURSEMENT', 'WITHDRAWAL') THEN amount ELSE 0 END), 0) as outflow FROM transactions`);
        const cashOnHand = parseFloat(liquidityRes.rows[0].inflow) - parseFloat(liquidityRes.rows[0].outflow);

        // Init PDF
        const doc = new PDFDocument({ margin: 50 });
        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', `attachment; filename=Executive_Report.pdf`);
        doc.pipe(res);

        // Header
        await drawHeader(doc, 'Executive Financial Report', req.user, sacco, serialNo);

        // --- CONTENT ---
        const startY = doc.y + 20;
        doc.font('Helvetica-Bold').fontSize(12).fillColor('#1e293b').text('1. FINANCIAL POSITION', 50, startY);
        doc.moveTo(50, startY + 15).lineTo(250, startY + 15).stroke();

        const row = (label, val, y, isCurrency = true) => {
            doc.font('Helvetica').fillColor('#333');
            doc.text(label, 60, y);
            const valStr = isCurrency ? `KES ${val.toLocaleString()}` : val;
            doc.font('Helvetica-Bold').text(valStr, 300, y, { align: 'right', width: 200 });
        };

        let y = startY + 30;
        row('Total Member Savings (Liability):', netSavings, y); y += 20;
        row('Total Revenue (Income):', totalRevenue, y); y += 20;
        row('Net Financial Assets:', netSavings + totalRevenue, y); y += 20;
        
        // Highlight Box for Liquidity
        doc.rect(50, y, 460, 25).fill('#ecfdf5').stroke('#10b981');
        doc.fillColor('#064e3b').text('AVAILABLE CASH ON HAND:', 60, y + 8);
        doc.text(`KES ${cashOnHand.toLocaleString()}`, 300, y + 8, { align: 'right', width: 200 });
        
        y += 50;

        doc.font('Helvetica-Bold').fontSize(12).fillColor('#1e293b').text('2. LOAN PORTFOLIO HEALTH', 50, y);
        doc.moveTo(50, y + 15).lineTo(250, y + 15).stroke();
        y += 30;

        row('Active Loans Count:', parseInt(loanStats.count), y, false); y += 20;
        row('Total Principal Disbursed:', parseFloat(loanStats.principal), y); y += 20;
        row('Total Interest Expected:', parseFloat(loanStats.interest), y); y += 20;
        
        // Risk Warning
        if (outstanding > 0) {
            y += 10;
            doc.rect(50, y, 460, 25).fill('#fef2f2').stroke('#ef4444');
            doc.fillColor('#b91c1c').text('OUTSTANDING LOAN RISK:', 60, y + 8);
            doc.text(`KES ${outstanding.toLocaleString()}`, 300, y + 8, { align: 'right', width: 200 });
        }

        // --- FOOTER SIGNATURES ---
        y += 100;
        doc.fontSize(10).fillColor('black');
        doc.text('Authorized Signature:', 50, y);
        doc.moveTo(160, y + 10).lineTo(300, y + 10).stroke(); // Line
        
        doc.text('Date:', 350, y);
        doc.moveTo(380, y + 10).lineTo(500, y + 10).stroke(); // Line

        doc.end();

    } catch (err) {
        console.error(err);
        if (!res.headersSent) res.status(500).json({ error: "Failed to generate report" });
    }
});

// ROUTE 3: ADMIN SUMMARY JSON (Keep existing for Dashboard display)
router.get('/summary', authenticateUser, async (req, res) => {
    // ... (Keep the exact code from previous step for JSON response) ...
    // If you need it again, I can paste it, but the logic is identical to the PDF one above.
    // For safety, I will include a minimal version here to prevent the route from missing.
    
    try {
        if (!['ADMIN', 'CHAIRPERSON', 'TREASURER'].includes(req.user.role)) return res.status(403).json({ error: "Denied" });

        const savingsRes = await db.query("SELECT COALESCE(SUM(amount), 0) as total FROM deposits WHERE status = 'COMPLETED' AND type = 'DEPOSIT'");
        const revenueRes = await db.query("SELECT COALESCE(SUM(amount), 0) as total FROM transactions WHERE type IN ('FINE', 'PENALTY', 'REGISTRATION_FEE', 'LOAN_FORM_FEE', 'FEE_PAYMENT')");
        const liquidityRes = await db.query(`SELECT COALESCE(SUM(CASE WHEN type IN ('DEPOSIT', 'LOAN_REPAYMENT', 'FINE', 'PENALTY', 'REGISTRATION_FEE') THEN amount ELSE 0 END), 0) as inflow, COALESCE(SUM(CASE WHEN type IN ('LOAN_DISBURSEMENT', 'WITHDRAWAL') THEN amount ELSE 0 END), 0) as outflow FROM transactions`);
        const loansRes = await db.query(`SELECT COUNT(*) as count, COALESCE(SUM(amount_requested), 0) as principal, COALESCE(SUM(interest_amount), 0) as interest, COALESCE(SUM(amount_repaid), 0) as repaid, COALESCE(SUM(total_due), 0) as total_due FROM loan_applications WHERE status = 'ACTIVE'`);
        const membersRes = await db.query("SELECT COUNT(*) as count FROM users WHERE role != 'ADMIN'");

        res.json({
            generated_at: new Date(),
            membership_count: parseInt(membersRes.rows[0].count),
            financials: {
                net_savings: parseFloat(savingsRes.rows[0].total),
                total_revenue: parseFloat(revenueRes.rows[0].total),
                financial_position: parseFloat(savingsRes.rows[0].total) + parseFloat(revenueRes.rows[0].total),
                cash_on_hand: parseFloat(liquidityRes.rows[0].inflow) - parseFloat(liquidityRes.rows[0].outflow),
                loan_portfolio: {
                    active_loans_count: parseInt(loansRes.rows[0].count),
                    total_disbursed_active: parseFloat(loansRes.rows[0].principal),
                    total_interest_charged: parseFloat(loansRes.rows[0].interest),
                    total_repaid_active: parseFloat(loansRes.rows[0].repaid),
                    outstanding_balance: parseFloat(loansRes.rows[0].total_due) - parseFloat(loansRes.rows[0].repaid)
                }
            }
        });
    } catch(e) { res.status(500).json({error: "Error"}); }
});

module.exports = router;